import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavbarWrapper from "./components/NavbarWrapper";
import FooterVisibility from "./components/FooterVisibility";
import NavigationFade from "./components/NavigationFade";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MediaKulture",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Providers>
          <NavbarWrapper />
          {children}
          <FooterVisibility />
          <NavigationFade />
        </Providers>
      </body>
    </html>
  );
}
